### ISSUE TITLE
Is batch decorator deprecated? 

### ISSUE THREAD

**Issue by jinwonkim93** [triton-inference-server/pytriton#10]
**Description**

After updating to 0.2.0 infer_func class with batch decorator raise error
![image](https://github.com/triton-inference-server/pytriton/assets/26476095/9762c3d6-f72d-4a77-a921-5d174e64ccaa)

But it works fine without decorator.

**Comment by piotrm-nvidia** [comment]
The ``batch`` decorator is still supported.

The new feature for processing HTTP custom parameters and headers was added: https://github.com/triton-inference-server/pytriton/commit/b494fc251007af03c34a0d0202c1e4f6845892d1

It changes logic for decorator internals and signatures of some functions. It is possible that this change has some unexpected side effect, which causes new error in your code.

I can't reproduce your scenario.

Would you be so kind to create small code example, which reproduces the error?

**Comment by jinwonkim93** [comment]
I tried to reproduce with sample code, i was not able to reproduce. i think it is not batch decorator problem. thank you for help
