### ISSUE TITLE
Load python backend models when pytriton starts

### ISSUE THREAD

**Issue by oeway** [triton-inference-server/pytriton#11]
**Is your feature request related to a problem? Please describe.**
We would like to load exiting triton model repository with a few python_backend models when we start pytriton. We would like to do this in colab.

**Describe alternatives you've considered**
We can potentially run a docker to spin up a triton server, but it's in colab where we can not run docker.

@ctr26

**Comment by jkosek** [comment]
@oeway @ctr26 Could you describe how your use case differ from loading the models in main Python thread, where Triton() object is created, instead of using the Python Backend models? Each model can be bind as separate inference callable in PyTriton. Would in such case models be available in colab?

**Comment by jkosek** [comment]
Thanks for explanation @oeway. Yes, you can use your own model repository path in `TritonConfig` which I see fill the need. Closing in such case.
