### ISSUE TITLE
Can I use pytriton to deploy models to a remote server?

### ISSUE THREAD

**Issue by gerasim13** [triton-inference-server/pytriton#12]
While I find the PyTriton library convenient, my plan is not to raise the server using the python process on the same machine as the backend system. Instead, I plan on running triton on a separate machine and want to know if it is possible to deploy models to it using PyTriton. Can you provide guidance on how to achieve this?

**Comment by jkosek** [comment]
Could you describe a bit more your use case? Would be nice to understand why you would like to pursue this way instead of running each model on separate PyTriton instance. Thanks!

**Comment by gerasim13** [comment]
> Reference in

I utilize numerous models integrated with self-created backends in C++. Besides this, I only have access to a single hardware server. While I could use Docker, I am unsure of the benefits it provides. Nvidia Triton Inference Server enables parallel execution of various models.

**Comment by piotrm-nvidia** [comment]
You can run all your C++ backends in with one instance of Triton in single machine:

Docker instance start:
```
docker run -it --ipc=host --ulimit memlock=-1 --ulimit stack=67108864  --shm-size 1G --gpus all nvcr.io/nvidia/pytorch:23.03-py3  bash
```
Pytriton installation:
```
pip install nvidia-pytriton
```


Server script ``server.py``:

```python
import logging
import numpy as np
from pytriton.decorators import batch
from pytriton.model_config import ModelConfig, Tensor
from pytriton.triton import Triton

logger = logging.getLogger("examples.identity_python.server")
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(name)s: %(message)s")


@batch
def _backend_one(**inputs):  # noqa: N803
    # Bind your backend_one C++ code here to python
    return {
        "OUTPUT_1": inputs["INPUT_1"],
    }

@batch
def _backend_two(**inputs):  # noqa: N803
    # Bind your backend_two C++ code here to python
    return {
        "OUTPUT_1": inputs["INPUT_1"],
    }


with Triton() as triton:
    logger.info("Loading Identity model.")
    triton.bind(
        model_name="Backend_one",
        infer_func=_backend_one,
        inputs=[
            Tensor(dtype=np.float64, shape=(-1,)),
        ],
        outputs=[
            Tensor(dtype=np.float64, shape=(-1,)),
        ],
        config=ModelConfig(max_batch_size=128),
    )
    triton.bind(
        model_name="Backend_two",
        infer_func=_backend_two,
        inputs=[
            Tensor(dtype=np.float64, shape=(-1,)),
        ],
        outputs=[
            Tensor(dtype=np.float64, shape=(-1,)),
        ],
        config=ModelConfig(max_batch_size=128),
    )
    logger.info("Serving inference")
    triton.serve()
```
Start server in background:
```
python3 server.py &
```

Client script ``client.py``: 
```python
import numpy as np
from pytriton.client import ModelClient
client_backend_one = ModelClient("localhost:8000", "Backend_one")
client_backend_two = ModelClient("localhost:8000", "Backend_two")
result_backend_one = client_backend_two.infer_batch(np.array([[1.0]]))
result_backend_two = client_backend_two.infer_batch(np.array([[1.0]]))
print("One", result_backend_one)
print("Two", result_backend_two)
```

Run client code:
```
python3 client.py
```

Output:
```
One {'OUTPUT_1': array([[1.]])}
Two {'OUTPUT_1': array([[1.]])}
```

Does this example cover your use case?

**Comment by piotrm-nvidia** [comment]
We provide a catalog with [folder](https://github.com/triton-inference-server/pytriton/tree/main/examples). Please check if there is one that meets your requirements.

Tokenizer is used in HuggigFace BERT JAX [example](https://github.com/triton-inference-server/pytriton/blob/main/examples/huggingface_bert_jax/server.py#L42).

Please create a new thread as **Feature request** in the [Issues](https://github.com/triton-inference-server/pytriton/issues/new/choose) section with a description of example you need, if this is not sufficient.

**Comment by gerasim13** [comment]
> You can run all your C++ backends in with one instance of Triton in single machine:
> 
> Docker instance start:
> 
> ```
> docker run -it --ipc=host --ulimit memlock=-1 --ulimit stack=67108864  --shm-size 1G --gpus all nvcr.io/nvidia/pytorch:23.03-py3  bash
> ```
> 
> Pytriton installation:
> 
> ```
> pip install nvidia-pytriton
> ```
> 
> Server script `server.py`:
> 
> ```python
> import logging
> import numpy as np
> from pytriton.decorators import batch
> from pytriton.model_config import ModelConfig, Tensor
> from pytriton.triton import Triton
> 
> logger = logging.getLogger("examples.identity_python.server")
> logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(name)s: %(message)s")
> 
> 
> @batch
> def _backend_one(**inputs):  # noqa: N803
>     # Bind your backend_one C++ code here to python
>     return {
>         "OUTPUT_1": inputs["INPUT_1"],
>     }
> 
> @batch
> def _backend_two(**inputs):  # noqa: N803
>     # Bind your backend_two C++ code here to python
>     return {
>         "OUTPUT_1": inputs["INPUT_1"],
>     }
> 
> 
> with Triton() as triton:
>     logger.info("Loading Identity model.")
>     triton.bind(
>         model_name="Backend_one",
>         infer_func=_backend_one,
>         inputs=[
>             Tensor(dtype=np.float64, shape=(-1,)),
>         ],
>         outputs=[
>             Tensor(dtype=np.float64, shape=(-1,)),
>         ],
>         config=ModelConfig(max_batch_size=128),
>     )
>     triton.bind(
>         model_name="Backend_two",
>         infer_func=_backend_two,
>         inputs=[
>             Tensor(dtype=np.float64, shape=(-1,)),
>         ],
>         outputs=[
>             Tensor(dtype=np.float64, shape=(-1,)),
>         ],
>         config=ModelConfig(max_batch_size=128),
>     )
>     logger.info("Serving inference")
>     triton.serve()
> ```
> 
> Start server in background:
> 
> ```
> python3 server.py &
> ```
> 
> Client script `client.py`:
> 
> ```python
> import numpy as np
> from pytriton.client import ModelClient
> client_backend_one = ModelClient("localhost:8000", "Backend_one")
> client_backend_two = ModelClient("localhost:8000", "Backend_two")
> result_backend_one = client_backend_two.infer_batch(np.array([[1.0]]))
> result_backend_two = client_backend_two.infer_batch(np.array([[1.0]]))
> print("One", result_backend_one)
> print("Two", result_backend_two)
> ```
> 
> Run client code:
> 
> ```
> python3 client.py
> ```
> 
> Output:
> 
> ```
> One {'OUTPUT_1': array([[1.]])}
> Two {'OUTPUT_1': array([[1.]])}
> ```
> 
> Does this example cover your use case?

I have created a C++ backend code using the C++ API provided by Triton Inference Server. I developed it based on the code available at https://github.com/triton-inference-server/backend/blob/main/examples/backends/minimal/src/minimal.cc. Are you suggesting that I export the C++ functions and call them from Python? Or can I generate a model configuration using PyTriton, deploy it, and use it in the same way I am currently using it without having to export C++ functions?

**Comment by piotrm-nvidia** [comment]
If you have developed a custom backend for Triton Inference server, you cannot use pyTriton to interact with it directly. PyTriton is designed for python backend that Triton supports. To use your custom backend, you have two options:

- You can write your own C++ code that uses the Triton C++ API to communicate with the server and your backend. This way, you do not need any Python code at all.
- You can create a Python binding for your C++ code and use pyTriton to set up the server configuration. This way, you can still use Python for some parts of your workflow, but you need to maintain the binding between Python and C++.

Regardless of which option you choose, you can use the ModelClient class to send inference requests to your custom backend.
