### ISSUE TITLE
How to use postman or use json file request to request server？

### ISSUE THREAD

**Issue by seawater668** [triton-inference-server/pytriton#13]
Convert the image to base64 and send it to the post server in the form of json, which is difficult to achieve in triton

**Comment by jkosek** [comment]
Hi @seawater668, have you maybe reviewed example with [Stable Diffusion](https://github.com/triton-inference-server/pytriton/tree/main/examples/huggingface_stable_diffusion)? You can encode image to base64 and send it to server, where the data can be decoded inside the inference callable to desired form.

As Triton support `application/json` format you should be able to send the data directly from postman placing the encoded image as a value of input request. Please, review the [Quick Start](https://github.com/triton-inference-server/pytriton/tree/main#quick-start) where a JSON data content is presented which is later sent using curl to server.

**Comment by yangxianpku** [comment]
You can use FastAPI to accept requests and internally submit them to Triton, which can improve the diversity of request parameters！
