### ISSUE TITLE
TypeError: a bytes-like object is required, not 'tuple'

### ISSUE THREAD

**Issue by rjac-ml** [triton-inference-server/pytriton#14]
I am receiving the following error when receiving multiple request. 
```
Failed to process the request(s) for model instance 'MODEL_0', message: TritonModelException: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pytriton/proxy/inference_handler.py", line 124, in run
    output_tensor_infos = self.shm_response_manager.to_shm(
  File "/usr/local/lib/python3.8/dist-packages/pytriton/proxy/communication.py", line 259, in to_shm
    return [
  File "/usr/local/lib/python3.8/dist-packages/pytriton/proxy/communication.py", line 261, in <listcomp>
    {
  File "/usr/local/lib/python3.8/dist-packages/pytriton/proxy/communication.py", line 262, in <dictcomp>
    input_name: self._wrap_array(req_res_index, input_name, req_resp.data[input_name])
  File "/usr/local/lib/python3.8/dist-packages/pytriton/proxy/communication.py", line 310, in _wrap_array
    buf[:required_buffer_size] = serialized_np_array
TypeError: a bytes-like object is required, not 'tuple'
```

Should this be manage by the --max-batch-size param?
or I am missing another concurrent param when deploying?

This is the dockerfile
```docker
ARG FROM_IMAGE_NAME=nvcr.io/nvidia/pytorch:23.04-py3
ARG BUILD_FROM

FROM ${FROM_IMAGE_NAME} as base
WORKDIR /opt/app

FROM base as install-from-pypi
RUN pip install -U nvidia-pytriton

FROM install-from-pypi AS image

ENV PYTHONUNBUFFERED=1
WORKDIR /opt/app

COPY install.sh /opt/app
RUN /opt/app/install.sh

COPY client.py /opt/app
COPY server.py /opt/app

ENTRYPOINT ["python","server.py"]
```

**Comment by jkosek** [comment]
@rjac-ml could you share model bind configuration and inference callable signature (including how the outputs are returned) defined in `server.py`?

**Comment by jr4c** [comment]
Hey, @jkosek  I figure out the problem, the inference function was returning a batch of a size different from the input batch size. meaning that if I got an input batch of 10, the returning object was just of size 1. (was a coding error inside the inference function).

**Comment by rjac-ml** [comment]
Hey, @jkosek I figure out the problem, the inference function was returning a batch of a size different from the input batch size. meaning that if I got an input batch of 10, the returning object was just of size 1. (was a coding error inside the inference function).

**Comment by jkosek** [comment]
Closing the issue. Please, re-open if you find any other problems. Thanks!
