### ISSUE TITLE
Model Analyzer compatibility

### ISSUE THREAD

**Issue by matty-rose** [triton-inference-server/pytriton#15]
Is it possible to use the model analyzer tool (https://github.com/triton-inference-server/model_analyzer) to help optimize models deployed with PyTriton? If so is there a quick-start or example available anywhere?

**Comment by nv-blazejkubiak** [comment]
Currently PyTriton doesn’t support Model Analyzer as in most cases Model Analyzer has to modify model config and load/unload models (currently PyTriton has exclusive ownership of Triton process and load/unload schedule).
We would like to consider if we could add support for the Model Analyzer tool in the future, so please let us know what model parameters you would like to optimize (in this case we can focus on real user scenarios).

**Comment by matty-rose** [comment]
@nv-blazejkubiak thanks for answering - the priorities for me would definitely be optimizing the maximum batch size & the dynamic batching configuration (e.g. queue delay)

**Comment by weihanfeng** [comment]
Any updates on this?
