### ISSUE TITLE
is there any performance compare  table between pytriton depoly with original python depoly  example on sd, gpt, tts, detection etc?

### ISSUE THREAD

**Issue by foocker** [triton-inference-server/pytriton#16]
what's the pytriton done on performance optimization

**Comment by nv-blazejkubiak** [comment]
According to PyTriton overhead (compared to Python Backend deployment), there is one additional copy of the input and output tensors. During our tests, latency overhead was around 5%, but of course it may vary depending on the ratio between the model size and the IO size.

We don't have a comparison table for different model types as this would be quite a huge effort.
In the future we plan to reduce overhead by using the same shared memory block as Python Backend and also supporting zero-copy for GPU inputs.
