### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by riyaj8888** [triton-inference-server/pytriton#19]
**Description**

A clear and concise description of the bug.

**To reproduce**

If relevant, add a minimal example so that we can reproduce the error, if necessary, by running the code. For example:

```python
# server
from pytriton.decorators import batch
from pytriton.model_config import ModelConfig, Tensor
from pytriton.triton import Triton

@batch
def _infer_fn(**inputs):
    ...
    results_dict = model(**inputs)  # ex note: the bug is here, we expect to receive ...
    ...
    # note: observing results_dict as dictionary of numpy arrays
    return results_dict


with Triton() as triton:
    triton.bind(
        model_name="MyModel",
        infer_func=_infer_fn,
        inputs=[
            Tensor(name="in1", dtype=np.float32, shape=(-1,)),
            Tensor(name="in2", dtype=np.float32, shape=(-1,)),
        ],
        outputs=[
            Tensor(name="out1", dtype=np.float32, shape=(-1,)),
            Tensor(name="out2", dtype=np.float32, shape=(-1,)),
        ],
        config=ModelConfig(max_batch_size=128),
    )
    triton.serve()
```

```python
# client
import numpy as np
from pytriton.client import ModelClient

batch_size = 2
in1_batch = np.ones((batch_size, 1), dtype=np.float32)
in2_batch = np.ones((batch_size, 1), dtype=np.float32)

with ModelClient("localhost", "MyModel") as client:
    result_batch = client.infer_batch(in1_batch, in2_batch)
```

**Observed results and expected behavior**

Please describe the observed results as well as the expected results.
If possible, attach relevant log output to help analyze your problem.
If an error is raised, please paste the full traceback of the exception.

```

```

**Environment**

- OS/container version: [e.g., container nvcr.io/nvidia/pytorch:23.02-py3 / virtual machine with Ubuntu 22.04]
- Python interpreter distribution and version: [e.g., CPython 3.8 / conda 4.7.12 with Python 3.8 environment]
- PyTriton version: [e.g., 0.1.4 / custom build from source at commit ______]
- Deployment details: [e.g., multi-node multi-GPU setup on GKE / multi-GPU single-node setup in Jupyter Notebook]

**Additional context**
ERROR: Could not find a version that satisfies the requirement nvidia-pytriton

**Comment by pziecina-nv** [comment]
Hi @riyaj8888,
PyTriton has some environment requirements that are written in the installation guide: https://triton-inference-server.github.io/pytriton/0.2.1/installation/#prerequisites. Does your environment meet all the prerequisites? If yes, can you share more details about your environment? It would be helpful if you fill out the following template:

```
Environment

OS/container version: [e.g., container nvcr.io/nvidia/pytorch:23.02-py3 / virtual machine with Ubuntu 22.04]
Python interpreter distribution and version: [e.g., CPython 3.8 / conda 4.7.12 with Python 3.8 environment]
PyTriton version: [e.g., 0.1.4 / custom build from source at commit ______]
Deployment details: [e.g., multi-node multi-GPU setup on GKE / multi-GPU single-node setup in Jupyter Notebook]
```

**Comment by pziecina-nv** [comment]
The most common issue when such error appear is too old pip package. PyTriton uses manylinux platform tags compliant with [PEP-600](https://peps.python.org/pep-0600/) which are [supported by pip since 20.3](https://pip.pypa.io/en/stable/news/#v20-3). Older pip version would not able to handle this tags. 

pip installed from Ubuntu 20.04 apt repository is in version 20.0, thus need to be updated in order ex. with below commands

```
pip install --upgrade --user pip
# pip install --user installs binaries in $HOME/.local/bin, thus need to ensure it is in your $PATH
export PATH=$HOME/.local/bin:$PATH
```
