### ISSUE TITLE
How to unload models?

### ISSUE THREAD

**Issue by lfxx** [triton-inference-server/pytriton#21]
There is no `--model-control-mode` in TritonConfig

**Comment by jkosek** [comment]
PyTriton does not allow to unload model at the moment as in fact model is executed in the main Python process that start Triton.

Could you describe your use case?

**Comment by lfxx** [comment]
> PyTriton does not allow to unload model at the moment as in fact model is executed in the main Python process that start Triton.
> 
> Could you describe your use case?

finally,i know pytriton can never unload model since the model is not started by triton server.I have use supervisor to implement this function.

**Comment by jkosek** [comment]
Sounds good. Would you provide some more details about use case where you see the dynamic models loading/unloading is useful? This would give us broader view at this request. Thanks!

**Comment by lfxx** [comment]
> Sounds good. Would you provide some more details about use case where you see the dynamic models loading/unloading is useful? This would give us broader view at this request. Thanks!

Sure!This function can be quite useful on GPU mem urgent condition.When there is no request within oneday,unload the model to save mem.If pytriton can native support this function,the deploy code will be more elegent.@jkosek

**Comment by jkosek** [comment]
Got it. Could I ask how you control when load/unload model? What are the tools you are using? We mainly consider using Kubernetes and deploy 1 model per 1 container and would like to understand other technology stack. Thanks!
