### ISSUE TITLE
why python3.7 is not supported?

### ISSUE THREAD

**Issue by lfxx** [triton-inference-server/pytriton#23]
if there are some bugs in python3.7?

**Comment by jkosek** [comment]
@lfxx we use some functionality that is available from Python 3.8+.

Also, a side note, the Python 3.7 is now EOL: https://endoflife.date/python.

**Comment by lfxx** [comment]
> @lfxx we use some functionality that is available from Python 3.8+.
> 
> Also, a side note, the Python 3.7 is now EOL: [endoflife.date/python](https://endoflife.date/python).

Get it .Thanks!
