### ISSUE TITLE
some questions 

### ISSUE THREAD

**Issue by lfxx** [triton-inference-server/pytriton#24]
1.difference between infer_sample and infer_batch from the source code?i don't find difference between them.infer_sample will also try to batch the input if max_batch_size>1 which should be done by infer_batch.
2.in server.py,how could we return the results? the docs don't elaborate this.
for example,we have a result as below
```
imgs=np.ones((8，1920，1080，3),dtype=np.uint8)
```
which way should i use to return this value?
`return [imgs] or return dict(result=imgs)`
i define the triton_config as follow:
```
with Triton(config=triton_config) as triton:
        logger.info("Loading ResNet model.")
        triton.bind(
            model_name="ResNet",
            infer_func=resnet_factory(DEVICES),
            inputs=[
                Tensor(name="image", dtype=np.uint8, shape=(-1, -1, 3)),
            ],
            outputs=[
                Tensor(name="result", dtype=np.uint8, shape=(-1,)),
            ],
            config=ModelConfig(
                max_batch_size=32,
                batcher=DynamicBatcher(max_queue_delay_microseconds=5000),  # 5ms
            ),
        )
        logger.info("Serving inference")
        triton.serve()
```
Another question: 
When `result` key's shape is defined as
```
shape=(-1,)
shape=(-1,-1,-1,3)
shape=(-1,-1,-1,-1,3)
```
the server can always successfully return the results,this is very confusing.In the above situation,result key's shape should only be `(-1,-1,-1,3)`?
 3.i notice you add a CLI inference_timeout_s,this will raise timeout exception at client side.But the server side is still processing and can't receive new request.I recommend a more proper way which can raise timeout exception in thread at server side,When this happens,the server side will stop the processing immediately when receive new request. please refer to https://github.com/dr-luke/PyTimeoutAfter
4.What's the speed of sending request to server side from client?I decode the img at client and then send them to server side.I find  this is quite slow.The transport between client and server is really time consuming.

Sorry for so many quesitons.Thanks very much!

**Comment by pziecina-nv** [comment]
Hi @lfxx,
Thank you for your questions. They are valuable in helping us improve both the PyTriton documentation and the PyTriton itself. Please find our responses below:

1. PyTriton offers the `infer_sample` and `infer_batch` methods to provide user-friendly API of the ModelClient. These methods adapt the provided input data to match the ModelConfig. If the model expects data with a batch axis (`max_batch_size` > 1), a [new batch axis will be added](https://github.com/triton-inference-server/pytriton/blob/main/pytriton/client/client.py#L267) when using the `infer_sample` method.
2. The lack of result shape verification is responsible for this behavior. We are currently working on improvements regarding the verification of returned results.
3. Regarding the timeout issue, your observation is correct. Currently, we have only provided a timeout option on the client-side. However, implementing a server-side timeout is part of our roadmap.

    As a temporary solution, you can use request headers to pass the expected timeout to the server side and try to handle it within the inference function. Here is a sample code snippet:

    ```python
    # client script
    with ModelClient(
        url,
        model_name,
        inference_timeout=infer_timeout_s,
    ) as client:
        result = client.infer_batch(
            ...,
            headers={“inference-timeout-s”: infer_timeout_s}
        )
    
    # server script
    @batch
    def infer_batch(**inputs):
        ...    
    
    def infer_fn(requests):
        for request in requests:
            infer_timeout_s = request.parameters.get(“inference-timeout-s”)
            … 
            infer_batch([request])   # handle timeouts per request
    ```
    For breaking model inference function, you may try to use one these helper packages i.e. stopit, mentioned above PyTimeoutAfter, or some custom code.

    Please note that this solution has some drawbacks, interrupting model calls from `infer_fn` is sometimes not possible.
4. Can you share your benchmarks scripts (client.py and server.py)? 

    One common issue we’re observing is the creation of a new client for each inference call. During initialization or the first inference request, there is an exchange of metadata requests between the client and server, which can significantly impact inference performance.

    ```python    
    client = ModelClient()  # correct place to create client
    for data in dataset:
        # creating a model client before each request
        # will cause the model metadata to be retrieved again.
        # slow_client = ModelClient(...)  
        client.infer_sample(data)
    ```

**Comment by lfxx** [comment]
> Hi @lfxx, Thank you for your questions. They are valuable in helping us improve both the PyTriton documentation and the PyTriton itself. Please find our responses below:
> 
> 1. PyTriton offers the `infer_sample` and `infer_batch` methods to provide user-friendly API of the ModelClient. These methods adapt the provided input data to match the ModelConfig. If the model expects data with a batch axis (`max_batch_size` > 1), a [new batch axis will be added](https://github.com/triton-inference-server/pytriton/blob/main/pytriton/client/client.py?rgh-link-date=2023-07-20T21%3A01%3A56Z#L267) when using the `infer_sample` method.
> 2. The lack of result shape verification is responsible for this behavior. We are currently working on improvements regarding the verification of returned results.
> 3. Regarding the timeout issue, your observation is correct. Currently, we have only provided a timeout option on the client-side. However, implementing a server-side timeout is part of our roadmap.
>    As a temporary solution, you can use request headers to pass the expected timeout to the server side and try to handle it within the inference function. Here is a sample code snippet:
>    ```python
>    # client script
>    with ModelClient(
>        url,
>        model_name,
>        inference_timeout=infer_timeout_s,
>    ) as client:
>        result = client.infer_batch(
>            ...,
>            headers={“inference-timeout-s”: infer_timeout_s}
>        )
>    
>    # server script
>    @batch
>    def infer_batch(**inputs):
>        ...    
>    
>    def infer_fn(requests):
>        for request in requests:
>            infer_timeout_s = request.parameters.get(“inference-timeout-s”)
>            … 
>            infer_batch([request])   # handle timeouts per request
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    For breaking model inference function, you may try to use one these helper packages i.e. stopit, mentioned above PyTimeoutAfter, or some custom code.
>    Please note that this solution has some drawbacks, interrupting model calls from `infer_fn` is sometimes not possible.
> 4. Can you share your benchmarks scripts (client.py and server.py)?
>    One common issue we’re observing is the creation of a new client for each inference call. During initialization or the first inference request, there is an exchange of metadata requests between the client and server, which can significantly impact inference performance.
>    ```python
>    client = ModelClient()  # correct place to create client
>    for data in dataset:
>        # creating a model client before each request
>        # will cause the model metadata to be retrieved again.
>        # slow_client = ModelClient(...)  
>        client.infer_sample(data)
>    ```

1.very clear.
2.This is quite urgent,do we have a deadline?
3.i have used PyTimeoutAfter to temporary achieve this.Hope for offical implements.
4.finally,i find i decode the img to wrong format which consume lots of time.the speed between server and client is fast.
Thank you for your detailed explainment.

**Comment by jkosek** [comment]
@lfxx we are currently working on improving the outputs validation. No exact ETA at the moment, but we will let you know once is available. Thanks for the feedback!

**Comment by jkosek** [comment]
In the 0.2.4 version there is `strict=True` (default is False) flag in `triton.bind` method that enable strict validation of result. This include a shape and dtype verification.
