### ISSUE TITLE
Sagemaker example

### ISSUE THREAD

**Issue by enricorotundo** [triton-inference-server/pytriton#25]
Hi there, is there any worked example for running pytriton on Sagemaker? I see [the `TritonConfig` class](https://triton-inference-server.github.io/pytriton/0.2.1/api/#pytriton.triton.TritonConfig) has parameters like `allow_sagemaker`, `sagemaker_port`, and such; do you have any (basic) instructions on how to use them to share please?

**Comment by jkosek** [comment]
Hi @enricorotundo. We currently do not have an example how to use PyTriton with SageMaker. However what we can suggest is to follow this guide of running own model: https://github.com/aws/amazon-sagemaker-examples/blob/main/advanced_functionality/scikit_bring_your_own/scikit_bring_your_own.ipynb
and see how the SageMaker environment flags are matched on TritonConfig in here: https://github.com/triton-inference-server/server/blob/main/docker/sagemaker/serve
Based on the tutorials and the Triton serve the minimum what you would need is:

- server.py -  with implementation of serving of your model
- serve - file definition how to execute the server.py
- Dockerfile to build the image with all necessary dependencies and files

I believe having that you can create the Docker image and use it to serve the model. 

Please mind, we haven't tested this path yet.

**Comment by jkosek** [comment]
PyTriton brings Triton to user environment. You can simply write an inference function and start serving your model directly from your code. This is core difference between PyTriton and Python Backend.
