### ISSUE TITLE
Does pytriton support hot loading models?

### ISSUE THREAD

**Issue by Fjallraven-hc** [triton-inference-server/pytriton#27]
Haven't seen any doc/api concerned about dynamic load/unload models, after the triton server is started.
Does pytriton support this feature or haven't developed yet?

**Comment by piotrm-nvidia** [comment]
There is already similar question:

https://github.com/triton-inference-server/pytriton/issues/21

**Comment by piotrm-nvidia** [comment]
We have feature request template so it can be very helpful for us, if you can use it and describe scenarios, when loading/unloading is useful and what features are helpful.


We were discussing some questions about this feature:
* How many models do you like to have at one machine?
* Where model should be, when they are not loaded (CPU RAM, network storage)?
* Should pyTriton present model as loaded, when it is unloaded and load it when inference request arrives? (This will introduce very big latency for first request or timeout error.)
* Model can be always loaded at CPU RAM and serve requests with bigger latency but move to GPU when number of requests gets bigger?

**Comment by fighterhit** [comment]
I have the same question. Is there any solution now?

**Comment by fighterhit** [comment]
@piotrm-nvidia  I have the same question. Is there any solution now? Looking forward to your answers and solutions!


* How many models do you like to have at one machine?
In my case less than 10, and we use it in kubernetes pod.

* Where model should be, when they are not loaded (CPU RAM, network storage)?
It would be better if the user can customize the configuration, or provide some extensions. For example, we can put the RAM first, and then put the model on the disk or other network storage through the LRU algorithm.

* Should pyTriton present model as loaded, when it is unloaded and load it when inference request arrives? (This will introduce very big latency for first request or timeout error.)
It would be better if it can be replaced gracefully. For example, when a model needs to be hot-updated, the new model will accept new requests after the model is loaded, similar to nginx reload?

* Model can be always loaded at CPU RAM and serve requests with bigger latency but move to GPU when number of requests gets bigger?
From my point of view, this may not be necessary. After all, if there is a GPU, I will use the GPU as much as possible.
