### ISSUE TITLE
Are there any examples of using python multiprocessing to run multiple copies of model on same GPU

### ISSUE THREAD

**Issue by wilson97** [triton-inference-server/pytriton#28]
Hi, thanks for the library, this is much easier than regular triton.

Right now I'm trying to run multiple instances of the same model (concurrently) on one big GPU. Unfortunately the concurrency is not working, seems like a GIL issue. Seems I have to use python multiprocessing library to do it myself. Do you have any examples of doing this? I looked through the existing examples but didn't find anything.

**Comment by jkosek** [comment]
Hi @wilson97. Could you share a sample code how you are initialize the model for multi-instance execution? 

Here is a sample that create multiple instances of model and locate it on different devices: https://github.com/triton-inference-server/pytriton/tree/main/examples/multi_instance_linear_pytorch

You may try follow this example and just use same device identifier for new instances.

**Comment by wilson97** [comment]
I tried that example, basically I set DEVICES = ["cuda:0", "cuda:0"]. I was able to see two instances of my model running concurrently, but the actual speedup is not very good. With 1 model I get 1.8 iterations/s, but with the concurrent 2 models I get 1.0 iterations/s for each. So at the end of the day there is a slight throughput increase, but it's not what I was hoping for.

I also checked that the GPU utilization with 1 model is 37%, and with 2 (concurrent) models only goes up to 41%. This makes me think there's something blocking good concurrency from happening. I think it might be because I'm using the same pytorch model (same python object) in both triton models. Do you have any insight on this? Thanks.

**Comment by jkosek** [comment]
@wilson97 could you try to create separate Python objects similar like that:
```
model1 = torch.nn.Linear(20, 30).to(device).eval()
model2 = torch.nn.Linear(20, 30).to(device).eval()
```
and verify if that helps? This might be an issue that in fact you have a single model and basically you see performance only because of some improved scheduling of input data. Separate Python object should create two separate instances of model.

**Comment by wilson97** [comment]
I will try this. However for me this is not optimal solution even if it works. The reason is that each of my models consumes ~10GB GPU memory, so if I have to load more than one copy it is a big waste of GPU space. Any other possible solutions?

**Comment by jkosek** [comment]
Does increasing the batch size improve the GPU utilization?

Running concurrently models in separate processes or multiple objects of model will always cause GPU memory growth. I am not sure if sharing model weights is possible.

What I can suggest is to try optimize model for inference. Here is Model Navigator with Inplace Optimize feature which could help improve GPU utilization: https://github.com/triton-inference-server/model_navigator.

You can find there examples how to use it with ResNet50 and Stable Diffusion models:

https://github.com/triton-inference-server/model_navigator/tree/main/examples/15_inplace_resnet

https://github.com/triton-inference-server/model_navigator/tree/main/examples/16_inplace_stable_diffusion

Hope this can be useful.

**Comment by wilson97** [comment]
Increasing batch size does help, I am already doing that. I will take a
look at those examples.

Back to my original idea - can I use python multiprocessing queues/pipes to
share my 1 loaded model among separate model processes? Has anyone tried
something like this?

Thanks.

**Comment by jkosek** [comment]
Could you explain what you mean by model processes? 

If you would like to run model in multiple processes this would result in creating separate instance of the model per process. If you would run multiple threads and call the same model you would be limited by the concurrent access to the model.

The general approaches we are seeing it to run multiple copy of model objects or each copy in separate process. If you look for better GPU utilization under same (similar) memory usage my recommendation is to take a look at Model Navigator to optimize the model.

**Comment by wilson97** [comment]
Right, if I run multiple threads I will be limited by concurrent access to
the model. What if I run multiple subprocesses instead of threads? Will
that work?

**Comment by jkosek** [comment]
No, this won't help. When running predictions of model on GPU you need to wait with new batch until the previous batch execution is finished. Calling single model multiple times won't improve the performance. The throughput on GPU is improved through batching. That is why dynamic batching is one of the main features of PyTriton.

If you would like to improve further performance and GPU utilization you would need to convert model to different format (like TensorRT and this is where Model Navigator helps) or have multiple model objects copy (in single process or model object per process, but this will result in increase of GPU memory usage).

**Comment by jinluyang** [comment]
> @wilson97 could you try to create separate Python objects similar like that:
> 
> ```
> model1 = torch.nn.Linear(20, 30).to(device).eval()
> model2 = torch.nn.Linear(20, 30).to(device).eval()
> ```
> 
> and verify if that helps? This might be an issue that in fact you have a single model and basically you see performance improvement only because of some improved scheduling of input data. Separate Python object should create two separate instances of model.

Hello, I find that whether we use different model or use same model in triton.bind, different infer_fn will result in different processes. But as far as I know, it seems Triton Inference Server Pytorch backend use multi-threads as multi-instance, which can reduce the memory consumption. While Python backend and pytriton use multi-process in order to get rid of GIL. But there are cases like this where the model is too big for multi-process. And we want to optimize the GPU utilization. Using TensorRT or so will for sure optimize the compute effectiveness, but not surely achieve a high GPU utilization/ SM activity. Is there any way we can use multi-thread and use different cudaStream in different threads?
