### ISSUE TITLE
How to check if the server-side service is still online through the client-side?

### ISSUE THREAD

**Issue by lfxx** [triton-inference-server/pytriton#30]
How to check if the server-side service is still online through the client-side?

**Comment by jkosek** [comment]
You can use a `wait_for_model` method from our ModelClient. More here: https://github.com/triton-inference-server/pytriton/blob/main/pytriton/client/client.py#L196.

Would that work?

**Comment by lfxx** [comment]
> You can use a `wait_for_model` method from our ModelClient. More here: [`main`/pytriton/client/client.py#L196](https://github.com/triton-inference-server/pytriton/blob/main/pytriton/client/client.py?rgh-link-date=2023-08-10T16%3A25%3A36Z#L196).
> 
> Would that work?

this makes sense.Thank you.
