### ISSUE TITLE
OUTPUT triton: list or tuple or any kind of Iterables

### ISSUE THREAD

**Issue by dogky123** [triton-inference-server/pytriton#35]
Hello, i just want to ask if I can config triton return a list/tuple... instead of Tensor ? Please give me some docs if it is possible.

**Comment by jkosek** [comment]
The Triton API is designed to receive/return tensors. At the moment is not possible to return lists or tuples. The option we can suggest is to use [PyTriton](https://github.com/triton-inference-server/pytriton) or [Triton Python Backend](https://github.com/triton-inference-server/python_backend) to serve the model and implement conversion of inputs/outputs between list/tuple and tensors. Would that work?

**Comment by dogky123** [comment]
> The Triton API is designed to receive/return tensors. At the moment is not possible to return lists or tuples. The option we can suggest is to implement conversion of inputs/outputs between list/tuple and tensors inside the inference function. Would that work?

It would take more cost to do
