### ISSUE TITLE
Stub process 'REGIS_0' is not healthy

### ISSUE THREAD

**Issue by lfxx** [triton-inference-server/pytriton#37]
**Description**

Run this server in docker,and will exit after a while with the error above

**To reproduce**

It happened by chance and cannot be reproduced 100%.

**Environment**

- Python interpreter distribution and version: [conda 4.7.12 with Python 3.8 environment]
- pip version: [23.1.2]
- PyTriton version: [0.2.5]
- Deployment details: [single gpu A10]

**Additional context**
after first time,i solve this by adding "ipc=host" to dockercompose file.But afterwards,it happened by chance.Anyone come here to help me out!Thanks!

**Comment by pziecina-nv** [comment]
Hi lfxx, can you share more details on this issue:
- how you're starting docker with script hosting pytriton (exact docker command or sample of docker compose yaml file)
- obtained logs from failed job
- is fail happens on model initialization? during inference? first inference? after some time?

**Comment by lfxx** [comment]
> Hi lfxx, can you share more details on this issue:
> 
> * how you're starting docker with script hosting pytriton (exact docker command or sample of docker compose yaml file)
> * obtained logs from failed job
> * does fail happens on model initialization? during inference? first inference? after some time?

Thanks for your rapid reply.Finally,i realize i add "ipc=host" to docker in a wrong way.I have resloved this issue by adding this para correctly.
