### ISSUE TITLE
Client network and/or connection timeout is smaller than requested timeout_s. This may cause unexpected behavior.

### ISSUE THREAD

**Issue by lfxx** [triton-inference-server/pytriton#38]
**Is your feature request related to a problem? Please describe.**
i get this warning,can we provide a parameter to slience this warning,really annoying.

**Comment by pziecina-nv** [comment]
Hi, we plan to review codes for such warning and switch to `warnings` package. This way it can be selectively filtered + if needed still captured by logging.

**Comment by lfxx** [comment]
> Hi, we plan to review codes for such warning and switch to `warnings` package. This way it can be selectively filtered + if needed still captured by logging.

get it
