### ISSUE TITLE
TensorRT-LLM suport?

### ISSUE THREAD

**Issue by LouisCastricato** [triton-inference-server/pytriton#41]
**Is your feature request related to a problem? Please describe.**

I can't seem to find any examples of how to distribute models that are built for tensorrt-llm. Is this a possible thing and I am missing documentation for it?

**Describe the solution you'd like**

Either improve documentation on how to utilize pytriton with tensorrt-llm or explain why such a combination is non-desirable or ill-formed 

**Describe alternatives you've considered**

I've looked at the OPT-Jax example and have begun experimenting with using a Jax port of LLaMA 2 with that example.

**Comment by pziecina-nv** [comment]
Hi,
Thank you for your feature request. 

Current [TensorRT-LLM](https://github.com/NVIDIA/TensorRT-LLM) team's guidance is to use using the [TensorRT-LLM Backend](https://github.com/triton-inference-server/tensorrtllm_backend) to run models on Triton.

We're currently developing an example to demonstrate integrating TensorRT-LLM with PyTriton, which should help clarify this process.

**Comment by piotrm-nvidia** [comment]
TensorRT LLM support is possible from release 0.5.0. The [example](https://github.com/triton-inference-server/pytriton/tree/main/examples/tensorrt_llm#readme) was create to showcase PyTriton usage with NVIDIA TensoRT LLM.
