### ISSUE TITLE
how to use instance group

### ISSUE THREAD

**Issue by eshuka** [triton-inference-server/pytriton#5]
Hi

I have a question about instance_group.

In TIS, i'm using instance_group in config.pbtxt.

instance_group [{
                   count: 3,
                   kind: KIND_GPU 
}]

i want to use instance_group count 3 in single gpu in pytriton.

Is there a way to use instance_group as above in pytriton?

**Comment by pziecina-nv** [comment]
Hi,
it can be achieved by passing multiple inference callables to the `infer_func` paramter of the `bind` method. Please take a look at 
https://triton-inference-server.github.io/pytriton/0.1.5/deploying_models/#multi-instance-model-inference

**Comment by eshuka** [comment]
then, if i wanna two infer_func in 0 gpu device and one infer_func in 1 gpu device,

should create a devices list as follows?

infer_func=_infer_function_factory(devices=["cuda:0", "cuda:0", "cuda:1"])

**Comment by pziecina-nv** [comment]
right

**Comment by pziecina-nv** [comment]
@taehwakkwon can you share more context on your model environment? how do you currently start your model parts - as single process or separate processes run by mpirun/srun/torchrun?

For single process job you can use same approach as above:

```python
DEVICES = [("cuda:0", "cuda:1"),("cuda:2", "cuda:3"),("cuda:4", "cuda:5"),("cuda:6", "cuda:7"),]


class _InferFuncWrapper:
    def __init__(self, model: torch.nn.Module, device: str):
        self._model = model
        self._devices = devices

    @batch
    def __call__(self, **inputs):
        (input1_batch,) = inputs.values()
        input1_batch_tensor = torch.from_numpy(input1_batch).to(self._devices[0])
        output1_batch_tensor = self._model(input1_batch_tensor)
        output1_batch = output1_batch_tensor.cpu().detach().numpy()
        return [output1_batch]


def _infer_function_factory(devices: List[Tuple[str]]):
    infer_funcs = []
    for d1, d2 in devices:
        model = load_model(d1, d2)
        infer_funcs.append(_InferFuncWrapper(model=model, devices=devices))

    return infer_funcs
```
But there is a problem with setup with multiple processes as inference threads cannot communicate with them to perform call. 

We're working on "remote mode" feature which could handle such use case. Each script will connect to already run Triton Inference Server and handle requests from it.  We think this feature running on single node should be ready on end of July 2023.

![tp_multi_instance excalidraw](https://github.com/triton-inference-server/pytriton/assets/82216611/a947cb78-81da-4314-82dd-8e67b5f1ad1a)

**Comment by leafjungle** [comment]
> Hi, it can be achieved by passing multiple inference callables to the `infer_func` paramter of the `bind` method. Please take a look at https://triton-inference-server.github.io/pytriton/0.1.5/deploying_models/#multi-instance-model-inference

when infer_func=[func_1, func_1, func_1],  does it means 3 requests can be processed at the same time? (parallel=3)

(And if I want to make the server parallel=100, just repeat func_1 100 times?  that is so strange)

in other words, if func_1 takes 10 ms,   then the client sends 3 requests to the server, it will get the result in 10 ms + socket_time ?
