### ISSUE TITLE
The content of this document is incorrect

### ISSUE THREAD

**Issue by HJH0924** [triton-inference-server/pytriton#54]
The content of this [document ](https://github.com/triton-inference-server/pytriton/blob/main/examples/huggingface_dialogpt_streaming_pytorch/README.md) is incorrect.
![image-20240111174238622](https://github.com/triton-inference-server/pytriton/assets/73840153/c93faf3f-b104-472c-8478-48f44f820468)

**Comment by piotrm-nvidia** [comment]
Solved in release commit: https://github.com/triton-inference-server/pytriton/commit/1703c94254b53492eca0d3ba0ec3ffa689592e07
