### ISSUE TITLE
The content of this document is wrong

### ISSUE THREAD

**Issue by HJH0924** [triton-inference-server/pytriton#55]
The content of this [document ](https://github.com/triton-inference-server/pytriton/blob/main/examples/huggingface_stable_diffusion/README.md) is wrong
![image-20240111201537155](https://github.com/triton-inference-server/pytriton/assets/73840153/cb39048e-2a49-4c11-b240-0c76b4f9303f)

**Comment by piotrm-nvidia** [comment]
Solved in commit: https://github.com/triton-inference-server/pytriton/commit/1703c94254b53492eca0d3ba0ec3ffa689592e07
