### ISSUE TITLE
how to define a new api  andinput like flask

### ISSUE THREAD

**Issue by Pobby321** [triton-inference-server/pytriton#60]
I have a json input to pytriton like
{
    "requestId": "490290d1-8792-4542-b31d-e123e229bfd7",
    "inputs": {
        "sample": [
            {
                "id": "001",
                "samplequestion": "xxxxxx"
            }
        ],
        
    }
}
and want to define a new new api like http://xx.xx.xx.xx:xxxx/xx/xx/xx

how should i do

**Comment by jkosek** [comment]
Hey @Pobby321 the PyTriton is exposing standard Triton urls which are implementation of V2 Inference Protocol: https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/v2-protocol.html

At the moment there is no option to define own API endpoint.
