### ISSUE TITLE
double container in kubernetes

### ISSUE THREAD

**Issue by leafjungle** [triton-inference-server/pytriton#67]
pytriton requirments: glibc>=2.35, python>=3.8
but many python backends' environment does not match that, especially for the code developed long time ago.

Thus we need two containers (and two images) in one pod: 
one run pytriton( read request, check cache, dynamic batch, call user code in another container, response)
the other one run user's python backend codes.

Is that possible?

**Comment by jkosek** [comment]
Hi @leafjungle. Apologize for late response. Were you able to already find the solution?

We do have a Remote Mode for PyTriton that can attach to the existing Triton or PyTriton instance running on the same host: https://triton-inference-server.github.io/pytriton/latest/remote_triton/

If you are targeting the Kuberenetes you would most likely want to use a shared volume between containers in POD (for example [EmptyDir](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir)) where the shared memory socket would be created (is required for Triton binary to Python process communication). On PyTriton side you would need to point `workspace` argument to the shared directory: https://triton-inference-server.github.io/pytriton/latest/reference/triton/#pytriton.triton.RemoteTriton

Let me know if that would be helpful here.
