### ISSUE TITLE
Model instances question

### ISSUE THREAD

**Issue by tinsss** [triton-inference-server/pytriton#69]
Hi! 

Thanks for the amazing work on PyTriton!
I want to ask a few questions regarding how model instancing works under the hood. 

1. From the source code it seems like each inference function is wrapped to `InferenceHandler` which is a subclass of `th.Thread`. How do we get different processes running the inference from this?
2. In the multi instance inference [example](https://github.com/triton-inference-server/pytriton/blob/main/examples/multi_instance_resnet50_pytorch/server.py) each instance is a new python object. Why do wee need different objects in this case?

Thanks in advance!

**Comment by leafjungle** [comment]
I am also puzzled by this. 
"Multi-instance" means the server processes multiple requests in the same time, these requests share the same “infer_func”, it is nothing to do with "infer_func" to be a list ?
