### ISSUE TITLE
Support for DALI and TensorRT 

### ISSUE THREAD

**Issue by yangxianpku** [triton-inference-server/pytriton#7]
Hi: 

Are DALI and TensorRT currently supported? If so, can corresponding examples be provided in examples？ Thanks a lot.

**Comment by JanuszL** [comment]
Hi @yangxianpku,

Thank you for reaching out. We are working on an example with DALI. Stay tunned.

**Comment by jkosek** [comment]
@yangxianpku for TensorRT support you may want to review using [Model Navigator](https://github.com/triton-inference-server/model_navigator) and utilize runners for running inference through PyTriton.

Here is an example of optimizing model and serving it on PyTriton: https://github.com/triton-inference-server/model_navigator/tree/main/examples/05_optimize_and_serve_model_on_pytriton

**Comment by jkosek** [comment]
@yangxianpku to clarify because I think we haven't answered the initial question. The PyTriton can run any Python function so you can use Python API for DALI and TensorRT to server those models.

**Comment by pziecina-nv** [comment]
Hi @yangxianpku,
@szalpal prepared example with DALI https://github.com/triton-inference-server/pytriton/tree/main/examples/dali_resnet101_pytorch

**Comment by yangxianpku** [comment]
Thanks
