### ISSUE TITLE
Model is not initialized to GPU.

### ISSUE THREAD

**Issue by jaehyeong-bespin** [triton-inference-server/pytriton#77]
**Description**

The Tesla T4 GPU server is using pyriton. However, even though the triton server recognizes the existence of the GPU, it is a problem to allocate the model to the CPU during model initialization.

Below is the log when running the triton server.
![스크린샷 2024-06-24 오후 4 46 59](https://github.com/triton-inference-server/pytriton/assets/132559789/bfc4d802-7b57-41ef-80a0-0e32dd517373)

Looking at the log, it can be confirmed that the metrics of the triton server recognized GPU (GPU 0: Tesla T4).
However, it may be seen that all models are allocated to CPU (CPU device 0).
```
I0624 07:34:17.037166 1320065 python_be.cc:1977] TRITONBACKEND_ModelInstanceInitialize: bb8-embedder-nlu_0 (CPU device 0)
I0624 07:34:17.083562 1320065 python_be.cc:1977] TRITONBACKEND_ModelInstanceInitialize: bb8-embedder-assist-biencoder-query_0 (CPU device 0)
I0624 07:34:17.096001 1320065 python_be.cc:1977] TRITONBACKEND_ModelInstanceInitialize: bb8-embedder-assist-crossencoder_0 (CPU device 0)
I0624 07:34:17.117102 1320065 python_be.cc:1977] TRITONBACKEND_ModelInstanceInitialize: bb8-embedder-assist-biencoder-passage_0 (CPU device 0)
```

**To reproduce**

Below is the reproduction code for one model.

```python
from pathlib import Path
import numpy as np
import torch
from sentence_transformers import SentenceTransformer, CrossEncoder

from pytriton.decorators import batch
from pytriton.model_config import ModelConfig, Tensor, DeviceKind
from pytriton.model_config.triton_model_config import TritonModelConfig
from pytriton.model_config.parser import ModelConfigParser
from pytriton.triton import Triton, TritonConfig

# Load SentenceTransformer model 
nlu_embedder = SentenceTransformer('bespin-global/klue-sroberta-base-continue-learning-by-mnr', device=device)

@batch
def _infer_fn_nlu(sequence: np.ndarray):
    sequence = np.char.decode(sequence.astype("bytes"), "utf-8")  # need to convert dtype=object to bytes first
    sequence = sum(sequence.tolist(), [])

    embed_vectors = nlu_embedder.encode(sequence, device=device)

    return {'embed_vectors': embed_vectors}


with Triton(config= TritonConfig(allow_gpu_metrics=True)) as triton:
    triton.bind(
        model_name="bb8-embedder-nlu",
        infer_func=_infer_fn_nlu,
        inputs=[
            Tensor(name="sequence", dtype=bytes, shape=(1,)),
        ],
        outputs=[
            Tensor(name="embed_vectors", dtype=bytes, shape=(-1,)),
        ],
        # config=ModelConfig(max_batch_size=args.max_batch_size),
        config=ModelConfigParser.from_file(config_path=Path('./model_config/bb8-embedder-nlu.pbtxt')),
        strict=True
    )
```

At first, `ModelConfig()` was used for the config item at the time of `triton.bind()`, but due to the above-mentioned problem, a config.pbtxt file was created and model config information was assigned through `ModelConfigParser()`.

Below is the contents of the config.pbtxt file.
```
name: "bb8-embedder-nlu"
max_batch_size: 32
input {
  name: "sequence"
  data_type: TYPE_STRING
  dims: 1
}
output {
  name: "embed_vectors"
  data_type: TYPE_STRING
  dims: -1
}
instance_group {
  count: 1
  kind: KIND_GPU
  gpus: [ 0 ]
}
dynamic_batching {
}
backend: "python"
```
As you can see in the pbtxt file, even though the `instance_group` specified `Kind_GPU` in the `kind` entry, it is not assigned to the GPU.

The expected outcome is that the models are assigned as `GPU device 0`. How can I solve this?

**Environment**
- OS/container version: Debian GNU/Linux 11 (bullseye) in GCP VM instance
  - glibc version: ldd (Debian GLIBC 2.31-13+deb11u10) 2.31
- Python interpreter distribution and version: conda 24.5.0 with Python 3.8 environment

- Python interpreter distribution and version: [e.g., CPython 3.8 / conda 4.7.12 with Python 3.8 environment]
- pip version: 24.0
- PyTriton version: 0.2.5
- Deployment details: single-node GPU

**Additional context**
The result of the pbtxt generated within the `/.cache/pytriton/workspace ~/model_store` when you run the triton server.
![스크린샷 2024-06-24 오후 5 03 52](https://github.com/triton-inference-server/pytriton/assets/132559789/7afa3b7d-1adf-41ba-8991-20f35fc508e6)

Despite typing KIND_GPU directly into the model config file, it changes to KIND_CPU and works.

**Comment by bc-anam** [comment]
Having the exact same issue.

**Comment by piotrm-nvidia** [comment]
The issue you're experiencing stems from how PyTriton handles device assignments for models using the Python backend. Even though you've specified `instance_group { kind: KIND_GPU }` in your model configuration, the actual device usage for PyTriton inference callable is determined by your Python code, not the Triton configuration.

**Understanding the Issue:**

- **Triton Backend Initialization Logs:** When Triton logs show `TRITONBACKEND_ModelInstanceInitialize: bb8-embedder-nlu_0 (CPU device 0)`, it refers to the Triton backend instance, not necessarily where your model computations occur. For the Python backend, Triton initializes the model instance on the CPU but doesn't manage the device where your computations run.

- **Device Management in Python Backend:** For models using the Python backend, Triton doesn't automatically move your model or data to the GPU. It's up to your Python code to handle device placement explicitly.

**Solution:**

To ensure your model uses the GPU, you need to specify the device in your Python code. The sentece transformer can accept Numpy tensors and produces numpy tensor output for model loaded into GPU so you don't need to worry about data transfer between CPU and GPU but for other models you may need to move data between CPU and GPU.

**Updated Code Example:**

```python
from pathlib import Path
import numpy as np
import torch
from sentence_transformers import SentenceTransformer, CrossEncoder

from pytriton.decorators import batch
from pytriton.model_config import ModelConfig, Tensor, DeviceKind
from pytriton.model_config.triton_model_config import TritonModelConfig
from pytriton.model_config.parser import ModelConfigParser
from pytriton.triton import Triton, TritonConfig

# Added variable for device
device = torch.device("cuda:0")

# Load SentenceTransformer model 
nlu_embedder = SentenceTransformer('bespin-global/klue-sroberta-base-continue-learning-by-mnr', device=device)

@batch
def _infer_fn_nlu(sequence: np.ndarray):
   sequence = np.char.decode(sequence.astype("bytes"), "utf-8")  # need to convert dtype=object to bytes first
   sequence = sum(sequence.tolist(), [])

   embed_vectors = nlu_embedder.encode(sequence, device=device)

   return {'embed_vectors': embed_vectors}


with Triton(config= TritonConfig(allow_gpu_metrics=True)) as triton:
   triton.bind(
       model_name="bb8-embedder-nlu",
       infer_func=_infer_fn_nlu,
       inputs=[
           Tensor(name="sequence", dtype=bytes, shape=(1,)),
       ],
       outputs=[ # dtype modified to float32
           Tensor(name="embed_vectors", dtype=np.float32, shape=(-1,)),
       ],
       # config=ModelConfig(max_batch_size=args.max_batch_size),
       config=ModelConfigParser.from_file(config_path=Path('./model_config/bb8-embedder-nlu.pbtxt')),
       strict=True
   )
   # Serve call to block script added
   triton.serve()
```

**Client sample to load model**

My client code is:

```python
from pytriton.client import ModelClient
import numpy as np
cl = ModelClient("localhost", "bb8-embedder-nlu")
print(cl.model_config)
while True:
    result = cl.infer_sample(np.char.encode(["This is test message"], "utf-8"))
```

**Key Changes and Explanations:**

1. **Specify the Device:**
   ```python
   device = torch.device("cuda:0")
   ```
   This ensures that your model and tensors are moved to GPU device 0.

2. **Adjust the Output Tensor Definition:**
   - Changed `dtype` to `np.float32` to match the output type of the embeddings.

**Verifying GPU Usage:**

To confirm that your model is utilizing the GPU:

- **Monitor GPU Activity:**
  Use `nvidia-smi` or tools like `nvtop` to observe GPU memory usage and compute activity when the server is running and handling requests.

- **Test Inference:**
  Send inference requests and observe if the GPU usage increases correspondingly.

**Summary:**

Your models are not automatically assigned to GPU device 0 by Triton when using the Python backend, even if `KIND_GPU` is specified in the configuration. To solve this:

- Explicitly specify the GPU device in your Python code.
- Load your model onto the GPU.
- Move inputs to the GPU if necessary.
- Move outputs back to the CPU before returning them to Triton if needed.
- Use monitoring tools to confirm GPU usage.

By managing device placement in your code, you'll ensure that your models utilize the GPU as expected.

**Example of Confirming GPU Usage:**

```bash
# Install nvtop if not already installed
sudo apt-get install nvtop

# Run nvtop in the terminal
nvtop
```

You should see increased GPU utilization when your Triton server is running and handling inference requests.

When I run your model in my DGX machine with 8 GPUs I see that 24% of single GPU is used, when client script runs:
![gpu_usage_pytriton](https://github.com/user-attachments/assets/60afb152-d718-4b4a-8413-17f039b75c9a)
