### ISSUE TITLE
Dynamic Batching Seems Invalid?

### ISSUE THREAD

**Issue by yangxianpku** [triton-inference-server/pytriton#8]
Hi

I am trying to combine FastAPI with pytriton for Serving MobileNet_V2 TensorRT plan model. The inference service for the  model has enabled dynamic batching and disabled response caching. I used Python's locust tool for pressure testing and manually printed the tensor shape   and checked the  metrics by triton server itself. It seems that dynamic batching does not work. My example code is as follows. May I ask if there is any problem with my code?

###  Code Snippet

```python
# input shape: nx3x112x112, output shape=nx1000
with open("/mnt/data/codes/learning/python/pytriton/mobile_v2.plan", "rb") as f:
    runtime = trt.Runtime(trt.Logger(trt.Logger.ERROR))
    engine  = runtime.deserialize_cuda_engine(f.read())
    context = engine.create_execution_context() 


@batch
def infer_trt(**inputs: np.ndarray):
    (input1_batch,)           = inputs.values()
    input1_batch_tensor  = torch.from_numpy(input1_batch).to("cuda")

    print("input1_batch_tensor.shape = ", input1_batch_tensor.shape)

    context.set_binding_shape(0, input1_batch_tensor.shape)
    shape                   = context.get_binding_shape(1)
    output1_batch_tensor    = torch.empty(size=tuple(shape), dtype=torch.float32, device="cuda")

    bindings                = [None] * 2
    bindings[0]             = input1_batch_tensor.contiguous().data_ptr()
    bindings[1]             = output1_batch_tensor.contiguous().data_ptr()
    
    context.execute_async_v2(bindings, torch.cuda.current_stream().cuda_stream)
    output1_batch        = output1_batch_tensor.cpu().detach().numpy()
    return [output1_batch]

class ModelTrt(object):
    def __init__(self) -> None:
        self._run = False
        self.triton = Triton(config = triton_config)
        self.triton.bind(
            model_name = "MobileNet_v2",                  
            infer_func = infer_trt,
            inputs=[
                Tensor(dtype=np.float32, shape=(3, 112, 112)),    
            ],
            outputs=[
                Tensor(dtype=np.float32, shape=(1000, )),
            ],
            config = ModelConfig(batching = True,
                        max_batch_size = 16, 
                        batcher = DynamicBatcher(
                            max_queue_delay_microseconds = 50000,
                            preferred_batch_size = [8, 16],
                            preserve_ordering = True
                        ),
                        response_cache = False)
        )

     
    def run(self):
        if not self._run:
            self.triton.run()     
            self._run = True
        logger.info("Serving models")



    def __del__(self):
        if self._run:
            self.triton.stop()
        logger.info("Serving models stop")

server = ModelTrt()

server.run()

app   = FastAPI()

@app.post("/infer")
async def infer_image(request : Request):
    input1_batch = torch.randn(2, 3, 112, 112).cpu().detach().numpy() 

    with ModelClient("localhost", "MobileNet_v2") as client:
        logger.info("Sending request")
        result_dict = client.infer_batch(input1_batch)

    for output_name, output_batch in result_dict.items():
        # logger.info(f"{output_name}: {output_batch[0].shape}")
    return {output_name, output_batch[0].shape}
```

### TensorRT Plan Model
```bash
trtexec --onnx=mobile_v2.onnx --saveEngine=mobile_v2.plan  \
        --minShapes=input:1x3x112x112  \
        --optShapes=input:1x3x112x112 \
        --maxShapes=input:16x3x112x112 
```

###  Pressure Test

```python
# locust_perf.py
from locust import task, FastHttpUser

class WebService(FastHttpUser):
    host = "http://localhost:31010"

    @task
    def root(self):
        with self.client.request(method = "POST", url="/infer") as resp:
            assert  resp.status_code == 200
```

```bash
locust -f locust_perf.py --headless -u 10 -r 1
```

### Shape Info in Callable

![image](https://github.com/triton-inference-server/pytriton/assets/16118824/4a1237ed-fd1b-4752-bbdd-3e7fe8a16e7d)

### Metrices Info by Triton Server

```bash
curl localhost:8002/metrics > metrics.txt
```

nv_inference_request_success{model="MobileNet_v2",version="1"} 1078
nv_inference_request_failure{model="MobileNet_v2",version="1"} 0
nv_inference_count{model="MobileNet_v2",version="1"} 2156
nv_inference_exec_count{model="MobileNet_v2",version="1"} 1078

### Libs Version Info
```
nvidia-pytriton         0.2.0
tritonclient            2.34.0
```

**Comment by piotrm-nvidia** [comment]
ModelClient is synchronous function and it blocks your FastAPI server until inference is finished. You never send more than one concurrent request to your Triton instance:

https://stackoverflow.com/questions/66798981/working-of-concurrent-futures-threadpoolexecutor-max-workers-when-scaling-up-the

I will double check your code and share with you fixed version today.

**Comment by yangxianpku** [comment]
But during the stress test, I used locust to open 10 processes, which is equivalent to 10 concurrent requests.

**Comment by piotrm-nvidia** [comment]
ModelClient is synchronous. It blocks your main loop in FastAPI server.

**Comment by yangxianpku** [comment]
Thank you very much for your answer. I tried to change ModelClient to FuturesModelClient, implemented the function using the following code and finally succeeded. Thank you again!

```python
import numpy as np
import uvicorn
import logging
import torch
import uuid
import asyncio, concurrent
from   pytriton.client import FuturesModelClient

client       =  FuturesModelClient("localhost", "MobileNet_v2")
server.run()

app   = FastAPI()


def infer(data):
    return client.infer_batch(data).result()

@app.post("/infer")
async def infer_image(request : Request):
    input1_batch = torch.randn(2, 3, 112, 112).cpu().detach().numpy()   # Mobile_v2
    loop               = asyncio.get_running_loop()

    result_dict  = await loop.run_in_executor(None, infer, input1_batch)

    for output_name, output_batch in result_dict.items():
        pass
    return {output_name, output_batch[0].shape}
```

![image](https://github.com/triton-inference-server/pytriton/assets/16118824/d455f28e-8909-45ca-9b45-a73069b49e17)

**Comment by yangxianpku** [comment]
I'm very sorry, there's another new issue. I'm trying to develop a response cache now, but I still have a lot of reasoning going on. Am I not setting it correctly?

![image](https://github.com/triton-inference-server/pytriton/assets/16118824/25ffee3b-3aff-4e3a-b6e4-41f4f33497cc)



Additionally, I found that the previous version of PyTriton was able to set the size of the response cache, but the latest version 0.2.0 seems to not have a parameter set?

**Comment by jkosek** [comment]
Here is the information how to change the Triton configuration to increase the cache size: https://triton-inference-server.github.io/pytriton/0.2.0/binding_configuration/#response-cache

Please, try increase the cache size.

Also, you are using `torch.randn` for generating input tensors, please try to use some predefined set of values as most likely you may get lot of cache misses on random data.

**Comment by yangxianpku** [comment]
I'm sorry, I made a silly mistake. Thank you very much for your response.
