### ISSUE TITLE
May input tensor of the Callable be GPU addressed Tensor?

### ISSUE THREAD

**Issue by yangxianpku** [triton-inference-server/pytriton#9]
Hi

As shown in the title, can GPU Tensors be inputs of the Callable, such as torch.Tensor on device?   For a complex application with multiple backends connected in series, which will result in multiple H2D and D2H operations and waste a lot of time with  numpy.ndarray only scheme.

**Comment by piotrm-nvidia** [comment]
Inference Callable runs in Python process but Triton Inference Server is  executed in separate process. Proxy Backed is used to wrapper shared CPU memory as a way to pass tensors from Triton to Python.

See diagram:
![Diagram](https://github.com/triton-inference-server/pytriton/raw/b197f0c82d988c0fa4039de33fa798705336b1b1/docs/assets/hld.svg)

Orange and blue boxes are separate processes here.

1. Requests comes from client over HTTP/gRPC.
3. Triton passes it to Proxy Backend model.
4. Proxy handler passes it over shared memory to Python process.
5. Inference Callable calls Python code with numpy tensors.

See proxy model code:

https://github.com/triton-inference-server/pytriton/blob/b197f0c82d988c0fa4039de33fa798705336b1b1/pytriton/proxy/model.py#L170


See 

I will look for some work around for you and let you know today.

See shared CUDA memory GPRC client:
https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_grpc_cudashm_client.py#L110

See shared CUDA memory python backend:
https://github.com/triton-inference-server/python_backend/blob/main/README.md#interoperability-and-gpu-support

**Comment by yangxianpku** [comment]
thanks a lot
